### ISSUE TITLE
[website module request] mangabuddy

### ISSUE THREAD

**Issue by hesoyamma785** [dazedcat19/FMD#1154] opened 2022-12-13 06:49 UTC
### Name

mangabuddy

### Root URL

https://mangabuddy.com/

### Directory list URL

https://mangabuddy.com/latest

### Example manga info URL

https://mangabuddy.com/i-randomly-have-a-new-career-every-week

### Example chapter URL

https://mangabuddy.com/i-randomly-have-a-new-career-every-week/chapter-1

### Language

English

**Comment by Slasar41** [comment] 2024-09-06 13:33
Duplicate of https://github.com/dazedcat19/FMD2/issues/896

**Closed as completed by Slasar41** 2024-09-06 13:33 UTC
