### ISSUE TITLE
[bug-website module] reaperscan

### ISSUE THREAD

**Issue by hesoyamma785** [dazedcat19/FMD#1143] opened 2022-11-28 22:33 UTC
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22H2 x64

### Describe the bug

https://reaperscans.com/comics/4921-demonic-emperor
******************
![Screenshot 2022-11-29 015704](https://user-images.githubusercontent.com/77359705/204394754-117d86f9-75cb-4ccb-a42f-baa8540266ab.jpg)
and
![Screenshot 2022-11-29 020022](https://user-images.githubusercontent.com/77359705/204394841-82da2141-4dde-4027-8f71-c68d946459f6.jpg)

***************
if you go to the site you can see +320 chapters for this manhwa 
but when I want to download the chapters from fmd , there is only 192 chapters to download (from ch 131 - ch 322 )
************
![Screenshot 2022-11-29 015806](https://user-images.githubusercontent.com/77359705/204394909-51ffabb3-807f-485a-82ff-cce136748f0d.jpg)
and
![Screenshot 2022-11-29 015904](https://user-images.githubusercontent.com/77359705/204394929-8bf4ed7b-eb6f-425a-98d1-6d37dc4ab0c3.jpg)

**Comment by Slasar41** [comment] 2022-11-29 00:28
Duplicate of https://github.com/dazedcat19/FMD2/issues/1105

**Closed as completed by Slasar41** 2022-11-29 00:28 UTC
