### ISSUE TITLE
[bug-website module] AsuraScans

### ISSUE THREAD

**Issue by hesoyamma785** [dazedcat19/FMD#1020] opened 2022-06-29 08:17 UTC
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

![image](https://user-images.githubusercontent.com/77359705/176387148-4041a91a-8a53-4035-b313-540d98e3690b.png)
*********
![image](https://user-images.githubusercontent.com/77359705/176387231-36e393ad-f20d-401e-82d3-117e11c1ca19.png)
************
i cant download from my favorite list
and
i cant get new chapters of new manhwa from asurascans.
*********
https://www.asurascans.com/
https://www.asurascans.com/manga/sword-fanatic-wanders-through-the-night/

**Comment by Slasar41** [comment] 2022-08-24 19:04
Duplicate of https://github.com/dazedcat19/FMD2/issues/916

**Closed as completed by Slasar41** 2022-08-24 19:04 UTC
