### ISSUE TITLE
[bug-website module] tumangaonline

### ISSUE THREAD

**Issue by hidalg25** [dazedcat19/FMD#1467] opened 2024-05-21 03:10 UTC
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10

### Describe the bug

They cannot be viewed or downloaded.
![t](https://github.com/dazedcat19/FMD2/assets/115298872/ae301a90-0ad8-424a-b3f0-fa9c69258224)

**Comment by Slasar41** [comment] 2024-10-26 04:20
Duplicate of https://github.com/dazedcat19/FMD2/issues/522

**Closed as completed by Slasar41** 2024-10-26 04:20 UTC
