### ISSUE TITLE
[bug-website module] knightnoscanlation.com

### ISSUE THREAD

**Issue by YuIlHan** [dazedcat19/FMD#794] opened 2021-11-06 12:40 UTC
**Prerequisites**

- [ ] I'm using the latest version.
- [ ] All website modules are up to date.
- [ ] This is not temporary server issue.

**Describe the bug**
The site changed its layout so it changed the manga orders, so it's not working in the program.

Name: knightnoscanlation
Root URL:  https://knightnoscanlation.com/
Updated Directory list URL:  https://knightnoscanlation.com/bl/
Olded Directory list URL:         https://knightnoscanlation.com/mangas/

Example of new manga info URL: https://knightnoscanlation.com/bl/revenge-of-young-master-peng/
Example of old manga info URL : https://knightnoscanlation.com/mangas/revenge-of-young-master-peng/

**Comment by Slasar41** [comment] 2022-03-28 19:12
Duplicate of #560

**Closed as completed by Slasar41** 2022-03-28 19:12 UTC
