### ISSUE TITLE
[bug-website module] myreadingmanga.info

### ISSUE THREAD

**Issue by WhoAreYouPeople** [dazedcat19/FMD#945] opened 2022-03-25 15:06 UTC
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Arch Linux x86_64

### Describe the bug

Getting Title N/A when I try and load a URL. I have tried sending different cloudflare cookies and different URL profiles, but I won't load in the downloader.
For Example
https://myreadingmanga.info/drstn-sengen-shorts-dr-stone-dj-eng/

Title:
N/A

### Log

WARNING: WebsitBypass[cloudflare]: no Cloudflare solution found!
https://myreadingmanga.info/drstn-sengen-shorts-dr-stone-dj-eng/

This is from mitmproxy using a firefox cookie which is only cf_clearance

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error</title>
  <style type='text/css'>.cf-error-details{display:none}</style>
</head>
<body>
  <p>
    Upgrading! Please wait a moment We'll be back shortly!
    ::CLOUDFLARE_ERROR_1000S_BOX::
  </p>
</body>
</html>

**Comment by WhoAreYouPeople** [comment] 2022-03-25 15:15
This is the error when a chromium browser is used, as it includes, cf_clearance, cf_chl_, and cf_chl_prog

<!DOCTYPE html>




<html class="no-js" lang="en-US">

<head>
  <title>Please Wait... | Cloudflare</title>
  <meta name="captcha-bypass" id="captcha-bypass" />
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
  
  <style type="text/css">body{margin:0;padding:0}</style>
  
  <script>
    if (!navigator.cookieEnabled) {
      window.addEventListener('DOMContentLoaded', function () {
        var cookieEl = document.getElementById('cookie-alert');
        cookieEl.style.display = 'block';
      })
    }
  </script>
  
  <script type="text/javascript">
    //
    <![CDATA[
    (function(){
      window._cf_chl_opt={
        cvId: "2",
        cType: "managed",
        cNounce: "REDACTED",
        cRay: "REDACTED",
        cHash: "REDACTED",
        cUPMDTk: "\/otosan-no-kurorekishi-maemukina-do-m-wanwan-o-gifu-san-1-jp\/?__cf_chl_tk=REDACTED-REDACTED-REDACTED-REDACTED",
        REDACTED: "REDACTED",
        cTTimeMs: "REDACTED",
        cLt: "REDACTED",
        cRq: {
          ru: "REDACTED",
          ra: "REDACTED",
          rm: "REDACTED",
          d: "REDACTED",
          t: "REDACTED",
          m: "REDACTED",
          i1: "REDACTED",
          i2: "REDACTED",
          zh: "REDACTED",
          uh: "REDACTED",
          hh: "REDACTED",
        }
      };
    }());
    //]]>
  </script>
  <style type="text/css">
    #cf-wrapper #spinner {width:69px; margin:  auto;}
    #cf-wrapper #cf-please-wait{text-align:center}
    .attribution {margin-top: 32px;}
    .bubbles { background-color: REDACTED; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
    #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
    #cf-hcaptcha-container { text-align:center;}
    #cf-hcaptcha-container iframe { display: inline-block;}
    @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    #cf-wrapper #cf-bubbles { width:69px; }
    @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
    #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
    #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
  </style>
</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">

**Comment by Slasar41** [comment] 2022-03-25 19:21
Duplicate of #455

**Closed as completed** 2022-03-25 19:21 UTC
