### ISSUE TITLE
[website module request] mangafire.to

### ISSUE THREAD

**Issue by darkflee** [dazedcat19/FMD#1631] opened 2024-09-05 17:11 UTC
### Name

mangafire.to

### Root URL

https://mangafire.to/home

### Directory list URL

https://mangafire.to/home

### Example manga info URL

https://mangafire.to/manga/sono-bisque-doll-wa-koi-wo-suru.pmm4

### Example chapter URL

https://mangafire.to/read/sono-bisque-doll-wa-koi-wo-suru.pmm4/en/chapter-108

### Language

English

### Scanlation

No

### Additional details

beside english they had diff language option like mangadex

**Comment by Slasar41** [comment] 2024-09-06 12:03
Duplicate of https://github.com/dazedcat19/FMD2/issues/1384

**Closed as completed by Slasar41** 2024-09-06 12:03 UTC
