### ISSUE TITLE
[bug-website module] cannot download from isekaiscan.com

### ISSUE THREAD

**Issue by hamkah2c** [dazedcat19/FMD#1079] opened 2022-09-04 23:54 UTC
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

we can download the manga list from fmd, but if clicked there is none of chapter 
![image](https://user-images.githubusercontent.com/8862875/188338329-a4425c6c-a23f-4ebb-be1c-f814b14085ab.png)
the original website have the chapter
![image](https://user-images.githubusercontent.com/8862875/188338351-3de37451-d6b9-412b-9259-04f5a618e835.png)

### Log

=== Log Session Started at 05/09/2022 05:39:51 by Free Manga Downloader ===
05:39:51:044 INFO: "Free Manga Downloader" started [PID:17108]
05:39:51:047 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 2.0.31.0
               Product Version   : Win64
               Host Machine      : Windows 10 64-bit Build 19044
               FPC Version       : 3.3.1
               LCL Version       : 2.1.0.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : x86_64-Win64
               Build Time        : 2021/03/21 14:33:22
               Path              : D:\fmd\fmd.exe
               Process ID        : 17108
               MainThread ID     : 24684
06:37:15:459 INFO: WebsitBypass[cloudflare]: using webdriver "python" "lua\websitebypass\cloudflare.py" "https://isekaiscan.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
06:37:15:692 ERROR: WebsitBypass[cloudflare]: webdriver doesn't return anything (timeout)
https://isekaiscan.com/manga/shingan-no-yuusha/
06:37:16:011 INFO: WebsitBypass[cloudflare]: using webdriver "python" "lua\websitebypass\cloudflare.py" "https://isekaiscan.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
06:37:16:161 ERROR: WebsitBypass[cloudflare]: webdriver doesn't return anything (timeout)
https://isekaiscan.com/manga/shingan-no-yuusha/ajax/chapters
06:37:16:438 INFO: WebsitBypass[cloudflare]: using webdriver "python" "lua\websitebypass\cloudflare.py" "https://isekaiscan.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
06:37:16:532 ERROR: WebsitBypass[cloudflare]: webdriver doesn't return anything (timeout)
https://isekaiscan.com/wp-admin/admin-ajax.php
06:44:09:426 INFO: WebsitBypass[cloudflare]: using webdriver "python" "lua\websitebypass\cloudflare.py" "https://isekaiscan.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
06:44:09:507 ERROR: WebsitBypass[cloudflare]: webdriver doesn't return anything (timeout)
https://isekaiscan.com/manga/shingan-no-yuusha/
06:44:09:834 INFO: WebsitBypass[cloudflare]: using webdriver "python" "lua\websitebypass\cloudflare.py" "https://isekaiscan.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
06:44:09:920 ERROR: WebsitBypass[cloudflare]: webdriver doesn't return anything (timeout)
https://isekaiscan.com/manga/shingan-no-yuusha/ajax/chapters
06:44:10:268 INFO: WebsitBypass[cloudflare]: using webdriver "python" "lua\websitebypass\cloudflare.py" "https://isekaiscan.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
06:44:10:368 ERROR: WebsitBypass[cloudflare]: webdriver doesn't return anything (timeout)
https://isekaiscan.com/wp-admin/admin-ajax.php
06:44:17:511 INFO: WebsitBypass[cloudflare]: using webdriver "python" "lua\websitebypass\cloudflare.py" "https://isekaiscan.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
06:44:17:604 ERROR: WebsitBypass[cloudflare]: webdriver doesn't return anything (timeout)
https://isekaiscan.com/manga/shingan-no-yuusha/
06:44:17:821 INFO: WebsitBypass[cloudflare]: using webdriver "python" "lua\websitebypass\cloudflare.py" "https://isekaiscan.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
06:44:17:921 ERROR: WebsitBypass[cloudflare]: webdriver doesn't return anything (timeout)
https://isekaiscan.com/manga/shingan-no-yuusha/ajax/chapters
06:44:18:132 INFO: WebsitBypass[cloudflare]: using webdriver "python" "lua\websitebypass\cloudflare.py" "https://isekaiscan.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
06:44:18:221 ERROR: WebsitBypass[cloudflare]: webdriver doesn't return anything (timeout)
https://isekaiscan.com/wp-admin/admin-ajax.php
06:44:31:130 INFO: WebsitBypass[cloudflare]: using webdriver "python" "lua\websitebypass\cloudflare.py" "https://isekaiscan.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
06:44:31:235 ERROR: WebsitBypass[cloudflare]: webdriver doesn't return anything (timeout)
https://isekaiscan.com/manga/shiga-hime/
06:44:31:540 INFO: WebsitBypass[cloudflare]: using webdriver "python" "lua\websitebypass\cloudflare.py" "https://isekaiscan.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
06:44:31:632 ERROR: WebsitBypass[cloudflare]: webdriver doesn't return anything (timeout)
https://isekaiscan.com/manga/shiga-hime/ajax/chapters
06:44:31:952 INFO: WebsitBypass[cloudflare]: using webdriver "python" "lua\websitebypass\cloudflare.py" "https://isekaiscan.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
06:44:32:048 ERROR: WebsitBypass[cloudflare]: webdriver doesn't return anything (timeout)
https://isekaiscan.com/wp-admin/admin-ajax.php

**Comment by Slasar41** [comment] 2022-09-05 19:28
Cloudflare issue.
Duplicate of https://github.com/dazedcat19/FMD2/issues/990

**Closed as completed by Slasar41** 2022-09-05 19:28 UTC
