### ISSUE TITLE
[bug-website module] AsuraScans not updating the library

### ISSUE THREAD

**Issue by tsuzushii** [dazedcat19/FMD#1032] opened 2022-07-14 20:40 UTC
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

**System information**
Windows 11 

**Describe the bug**
Made sure to run with the latest version of MangaShiro.lua. Downloading the manga list from server fetches 30 entries that are not up to date. Updating the manga-list doesn't do anything.  I'm also unable to download any of the 30 results. Is this a known issue & are there any workarounds?

**Screenshots**
![image](https://user-images.githubusercontent.com/67488014/179078556-de6ca1d8-8816-48fd-b736-91703a91fa67.png)

**Comment by jillybeans** [comment] 2022-07-14 21:34
asura scans hasnt had a fix in awhile,  been down on fmd since feb 2022

**Comment by Slasar41** [comment] 2022-08-24 19:04
Duplicate of https://github.com/dazedcat19/FMD2/issues/916

**Closed as completed by Slasar41** 2022-08-24 19:04 UTC
