### ISSUE TITLE
[bug] Chapters missing and unable to download from Bato

### ISSUE THREAD

**Issue by Shellshock123** [dazedcat19/FMD#778] opened 2021-10-28 18:02 UTC
**System information**
Your operating system.

**Describe the bug**

https://user-images.githubusercontent.com/33560815/130310157-7933b0dd-3f72-4618-863d-f6b5d7dbff4e.png

Exactly what this guy is seeing but I'm trying to download from Bato. 
I've also noticed that you see the description Title/author/Genere etc... (Though you don't see the cover) If you click from the mangalist.

**Comment by Slasar41** [comment] 2021-11-14 18:51
Duplicate of https://github.com/dazedcat19/FMD2/issues/467

**Closed as completed by Slasar41** 2021-11-14 18:51 UTC
