### ISSUE TITLE
[bug-website module] Asurascans

### ISSUE THREAD

**Issue by hesoyamma785** [dazedcat19/FMD#987] opened 2022-05-06 08:11 UTC
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

asurascans website doesn't load in FMD2
![image](https://user-images.githubusercontent.com/77359705/167092811-985654d0-839b-4787-9d52-8379e9f8f0f6.png)
*************************
its like this the whole time 
whether i change my ip or not , it doesn't change anything
and the manhwa that were in favorites are now disabled
![image](https://user-images.githubusercontent.com/77359705/167093295-4d0a4248-e3c8-42c2-b63d-7a2ecb3d4bdc.png)

**Comment by Slasar41** [comment] 2022-08-24 19:04
Duplicate of https://github.com/dazedcat19/FMD2/issues/916

**Closed as completed by Slasar41** 2022-08-24 19:04 UTC
