### ISSUE TITLE
[bug-website module] Reaper Scans

### ISSUE THREAD

**Issue by mastafrooper** [dazedcat19/FMD#1101] opened 2022-10-06 21:20 UTC
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H2 X64

### Describe the bug

Reaper scans has a new website. Paths to series have changed.

**Comment by Slasar41** [comment] 2022-10-08 23:45
Duplicate of https://github.com/dazedcat19/FMD2/issues/1082.

**Closed as completed by Slasar41** 2022-10-08 23:45 UTC
