### ISSUE TITLE
[website module request] Mangabuddy

### ISSUE THREAD

**Issue by Aviean** [dazedcat19/FMD#1497] opened 2024-07-01 01:32 UTC
### Name

MangaBuddy

### Root URL

https://mangabuddy.com

### Directory list URL

https://mangabuddy.com/az-list

### Example manga info URL

https://mangabuddy.com/the-ten-great-emperors-at-the-beginning-are-all-my-apprentices

### Example chapter URL

https://mangabuddy.com/the-ten-great-emperors-at-the-beginning-are-all-my-apprentices/chapter-1

### Language

English

**Comment by Slasar41** [comment] 2024-09-06 13:33
Duplicate of https://github.com/dazedcat19/FMD2/issues/896

**Closed as completed by Slasar41** 2024-09-06 13:33 UTC
