### ISSUE TITLE
[bug-website module] Knight No Fansub directory change

### ISSUE THREAD

**Issue by YuIlHan** [dazedcat19/FMD#868] opened 2022-01-12 01:25 UTC
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10

### Describe the bug

**There was a directory change**

Name: Knight no Fansub
Root URL: https://knightnoscanlation.com/
Directory list URL: https://knightnoscanlation.com/biblioteca/

**BEFORE**
Example manga info URL: https://knightnoscanlation.com/bl/dark-lady/
Example chapter URL: https://knightnoscanlation.com/bl/dark-lady/capitulo-122/

**AFTER**
Example manga info URL: https://knightnoscanlation.com/sr/dark-lady/
Example chapter URL: https://knightnoscanlation.com/sr/dark-lady/capitulo-122/

Languages:
Spanish

**Comment by Slasar41** [comment] 2022-03-28 19:12
Duplicate of #560

**Closed as completed by Slasar41** 2022-03-28 19:12 UTC
